### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Lecale** [halonium/halonium#1]
I was interested to try out this package, but on compilation I saw this. What am I likely to be missing?

C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x2c3): undefined reference to `crc32'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x33e): undefined reference to `deflateInit2_'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x366): undefined reference to `deflate'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x416): undefined reference to `crc32'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x426): undefined reference to `deflateEnd'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x4c1): undefined reference to `deflateEnd'
        ... C:\Users\something\nimcache\halonium_r\libzip_all.c.o:libzip_all.c:(.text+0x16f4): undefined reference to `zError'

**Comment by jyapayne** [comment]
Hey, sorry, for some reason I didn't get notified of this issue.

I'll look into the issue!

**Comment by jyapayne** [comment]
Hey, if you're still interested, I think I fixed it. Please try version 0.2.0

**Comment by Lecale** [comment]
Ace! Everything works now. Well, everything I've tried so far :)

**Comment by jyapayne** [comment]
Awesome, let me know if there are other issues!
