### ISSUE TITLE
Closing session stalls on devel

### ISSUE THREAD

**Issue by planetis-m** [halonium/halonium#10]
Running the simple example doesn't quit correctly. There was a recent https://github.com/nim-lang/Nim/pull/16385 not sure if it's related. From the traceback though I would think the problem lies elsewhere.

```
[user@lenovo examples]$ ./simple
^CTraceback (most recent call last)
/home/user/code/repos/halonium/examples/simple.nim(19) simple
/home/user/code/repos/halonium/examples/simple.nim(17) main
/home/user/code/repos/halonium/src/haloniumpkg/webdriver.nim(674) stop
/home/user/code/repos/halonium/src/haloniumpkg/webdriver.nim(671) close
/home/user/code/repos/halonium/src/haloniumpkg/webdriver.nim(493) execute
/home/user/code/repos/halonium/src/haloniumpkg/webdriver.nim(377) execute
/home/user/code/repos/halonium/src/haloniumpkg/webdriver.nim(318) request
/home/user/build/Nim/lib/pure/httpclient.nim(1066) request
/home/user/build/Nim/lib/pure/httpclient.nim(1042) request
/home/user/build/Nim/lib/pure/httpclient.nim(1022) requestAux
/home/user/build/Nim/lib/pure/httpclient.nim(794) parseResponse
/home/user/build/Nim/lib/pure/net.nim(1570) recvLine
/home/user/build/Nim/lib/pure/net.nim(1530) readLine
/home/user/build/Nim/lib/pure/net.nim(1306) recv
/home/user/build/Nim/lib/pure/net.nim(1293) readIntoBuf
/home/user/build/Nim/lib/pure/net.nim(1289) uniRecv
SIGINT: Interrupted by Ctrl-C.
```

**Comment by jyapayne** [comment]
Thanks for the report. I performed a git bisect and found the offending PR to be [this](https://github.com/nim-lang/Nim/pull/16196). I opened an issue on the Nim issue tracker, but I created a workaround in the meantime in the latest version of halonium (0.2.3). Please check it out and let me know if it works!

**Comment by planetis-m** [comment]
Fyi, your halonium commit fixes the issue, however without the workaround after https://github.com/nim-lang/Nim/pull/16618 it's still not working

**Comment by jyapayne** [comment]
Hmm, thanks for letting me know. I'll take a look!

**Comment by jyapayne** [comment]
@planetis-m this should now be fixed in the latest devel for Nim: https://github.com/nim-lang/Nim/pull/16667#event-4258539056
