### ISSUE TITLE
Missing support for locating element by XPATH

### ISSUE THREAD

**Issue by andrewgohlk** [halonium/halonium#14]
Hi,
It seems that the halonium module doesn't support XPATH to locate the element from a web page.

**Comment by jyapayne** [comment]
You should be able to use it, but maybe it's not clear how.

```nim
let element = session.waitForElement("xpath here", strategy=XPathSelector)
```

Please let me know if this does not work.

**Comment by andrewgohlk** [comment]
I think it should be:
```
let element = session.waitForElement("xpath here", strategy=XPathSelector).get()
```

Also, after compiling & running my code, I hit:
```
Unexpected exception caught while executing command clickElement. Message: stale element reference: element is not attached to the page document
  (Session info: chrome=88.0.4324.150)
```

And subsequently:
```
Error: unhandled exception: stale element reference: element is not attached to the page document
  (Session info: chrome=88.0.4324.150) [StaleElementReferenceException]
```


I think need more documentation showing:
1) How to handle exception.
2) Timeout support

**Comment by jyapayne** [comment]
Hey, sorry it's been so long, I actually didn't see your update. I will create a separate issue for documentation and timeout support
