### ISSUE TITLE
UUID/Halonium install error. Im assuming Halonium uses UUIDs as a dependancy, which is wrecking when i attempt to install. (Windows)

### ISSUE THREAD

**Issue by INTIMSOCIAL** [halonium/halonium#18]
Building halonium/halonium.exe using c backend
\.nimble\pkgs2\uuids-0.1.11-393f5fcefbc8ad3cf167e59760144208ff8f9f76\uuids\urandom.nim(15, 8) Error: undeclared identifier: 'useWinUnicode'
candidates (edit distance, scope distance); see '--spellSuggest':
 (8, 2): 'NimNode'
    Error:  Aborting installation due to build failure.
   Failure: Validation failed.

**Comment by jyapayne** [comment]
This is a uuids issue. I have filed a pull request [here](https://github.com/pragmagic/uuids/pull/10)

**Comment by jyapayne** [comment]
Fixed with latest release.
