### ISSUE TITLE
`Window.execute` request arguments `windowHandle` seems take no effect

### ISSUE THREAD

**Issue by bung87** [halonium/halonium#24]
https://github.com/halonium/halonium/blob/0b00bcdcf565062d38ee3048cc3745e9bee22523/src/halonium/webdriver.nim#L720

I can't find the `windowHandle` document referrences on internet, so asking here.
open a new tab manually, loop through 2 windows, also tried switch window before execute script, only first window executed script. 

another problem is `currentWindow` always return first window, even I manually activated second tab.

**Comment by jyapayne** [comment]
Did you figure out what was going on?

**Comment by bung87** [comment]
yeah, my mistake, my script returns when domain not matches
