### ISSUE TITLE
Closing a session hangs

### ISSUE THREAD

**Issue by firyx** [halonium/halonium#28]
I have the following code (on Debian based MX Linux):

```nim
proc main() =
  let profileFlag = "--profile"
  let profileDir = "/home/user1/auto-project/Firefox-Profile-working"
  let options = firefoxOptions(args=[profileFlag, profileDir], logLevel=some("warn"))

  let session = createSession(
    browser = Firefox,
    driverExePath = some("/home/user1/.cache/selenium/geckodriver/linux64/0.34.0/geckodriver"),
    port = 4444,
    browserOptions = options,
    logLevel = "warn",
    logPath = "/home/user1/auto-project/xxx.log"
  )

  defer:
    session.stop()

  session.navigate("https://google.com")

  sleep(1000)

main()
```

When finished, closing the session (`session.stop()`) hangs closing the geckodriver process at this place:

file: `osproc.nim`

```nim
  proc close(p: Process) =
    if poParentStreams notin p.options:
      if p.inStream != nil:
        close(p.inStream)
      else:
        discard close(p.inHandle)

      if p.outStream != nil:
        close(p.outStream) # <=============+++===== this hangs
      else:
        discard close(p.outHandle)

      if p.errStream != nil:
        close(p.errStream)
      else:
        discard close(p.errHandle)
```

Is there a better way to start the process, so we can close it better, without hanging?
Or close it some better way?

Currently I have to `Ctrl+C` the running Nim program on terminal.

**Comment by firyx** [comment]
... I'm using Nim v2.0.4
and I'm very new to Nim.

**Comment by jyapayne** [comment]
Yes, there is some glitch with ORC that I haven't been able to figure out yet. If you compile with `nim c --gc:refc yourfile.nim`, it should work fine.

**Comment by firyx** [comment]
Nim (2.0.4) reports `--gc:refc` as deprecated,
so I'm using `--mm:refc`

and I can confirm, that the process closes correctly this way.
