### ISSUE TITLE
download file

### ISSUE THREAD

**Issue by sdmcallister** [halonium/halonium#7]
Is there a way to perform (automate) file downloads?

**Comment by jyapayne** [comment]
Short answer: no, not directly via the api.

Generally, downloading a file is not considered important to test and wastes bandwidth. [Selenium follows that line of thinking](https://www.selenium.dev/documentation/en/worst_practices/file_downloads/).

But there are ways to perform it manually, which generally it boils down to finding the download link (or button) on the page, then clicking it with the API or just manually hitting the URL with some HTTP library.

**Comment by sdmcallister** [comment]
Thanks for the fast reply. 

So if I click the download button, and the file dialogue appears, what commands are used to enter the file name / and then click save? Or am I misunderstanding and that can't be done.

You mention HTTP library. So the nim httpclient library, can that be used in conjunction with haloniun?  For example If I want to make a get request, is there some way to have the http client utilize or reference the browser state (not sure if that makes sense given the terms I'm using).  The scenario here is that certain components use js where others can just be accessed by httpclient?

**Comment by sdmcallister** [comment]
It turns out `session.navigate` triggers a download to the default dir and using `chromeOptions(experimentalOptions = %*{"prefs":{"download.default_directory":"C:\\the\\path\\"}})` allows for some organization. But as you say, this is worst practice.

What I don't understand is why, when using httpclient, `session.driver.client.getContent('url')` seems to not get the data. Does the session information not apply in this case?

**Comment by jyapayne** [comment]
>So if I click the download button, and the file dialogue appears, what commands are used to enter the file name / and then click save? Or am I misunderstanding and that can't be done.

That cannot be done, unfortunately.

> You mention HTTP library. So the nim httpclient library, can that be used in conjunction with haloniun? For example If I want to make a get request, is there some way to have the http client utilize or reference the browser state (not sure if that makes sense given the terms I'm using). The scenario here is that certain components use js where others can just be accessed by httpclient?

There's no way that I know of to use the browser state. I was simply referring to grabbing the url from the page's `a` tag. 

> What I don't understand is why, when using httpclient, session.driver.client.getContent('url') seems to not get the data. Does the session information not apply in this case?

I'm not quite sure what you mean. The `session.driver.client` does not use any state information from the session. You could use [this code](https://github.com/halonium/halonium/blob/master/src/haloniumpkg/webdriver.nim#L310) to issue a request via `session.driver.request(HttpGet, 'url')`, and use the experimental option you mentioned above to control where the download goes to. You can also use the `"download.prompt_for_download": false` option to not prompt for download. Does that help at all?

**Comment by sdmcallister** [comment]
Yes, this does help.  Sorry I'm such a Nim noob.  For this [code](https://github.com/halonium/halonium/blob/master/src/haloniumpkg/webdriver.nim#L310) what is the proper way to import the function given it is private?

**Comment by jyapayne** [comment]
> Yes, this does help. Sorry I'm such a Nim noob. For this code what is the proper way to import the function given it is private?

Ah yes, I missed that it was private. It might be okay to make it public. I can't really think of a reason not to.

Would you mind posting your solution in case other people are looking for the same thing?

**Comment by sdmcallister** [comment]
@jyapayne  
Sure, it's still a WIP but I will try to post something when I'm finished.
