### ISSUE TITLE
Chrome PageLoadStrategy not being parsed

### ISSUE THREAD

**Issue by KingDarBoja** [halonium/halonium#9]
Hi, I have been trying to figure out how to properly pass the `pageLoadStrategy` option parameter via the `chromeOptions` proc and right now trying something like:

```nim
  let session = createSession(
    Chrome,
    browserOptions = chromeOptions(
      pageLoadStrategy=option(plsEager),
      experimentalOptions=parseJson("""{"excludeSwitches": ["enable-logging"]}""")
    )
  )
```

But getting the following error:
```console
Error: unhandled exception: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: pageLoadStrategy [InvalidArgumentException]
```

Any suggestion regarding this? Cheers!

**Comment by jyapayne** [comment]
Hi, that turned out to be a bug in the options generator. Please try the latest version 2.2.0 and see if that fixes the issue!

**Comment by KingDarBoja** [comment]
Tested latest version (2.2.0) and yes, it does fixes the issue, thank you! Looking forward for more docs, so far using selenium as a guide to find the common functions and so on.
